<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination URLs_targetUrls.0</name>
   <tag></tag>
   <elementGuidId>e1d4f057-93b9-4972-92a8-679251f27511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='targetUrls']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#targetUrls</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f14740d4-7e2d-43f6-953c-822595b7fc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component InputText-module__input-text--tspjW</value>
      <webElementGuid>258e976e-343c-4380-aa6f-070a2d8030e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetUrls</value>
      <webElementGuid>f1fb89f7-8fa8-4e13-8e0d-f0f74cb5c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>targetUrls.0</value>
      <webElementGuid>52116e02-f650-44ce-9087-9c91b76d891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetUrls&quot;)</value>
      <webElementGuid>52e6f93d-2e27-4d56-82b7-c8d29a179e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='targetUrls']</value>
      <webElementGuid>b79dd57a-5f28-4ee5-b2d0-a5abc3dd11e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_3_content']/div/div[4]/div[2]/span/input</value>
      <webElementGuid>6ad30de3-e8d2-45be-99b8-8329288597ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span/input</value>
      <webElementGuid>23768f60-4474-4652-beca-38a9d82f2267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'targetUrls' and @name = 'targetUrls.0']</value>
      <webElementGuid>f1460629-5897-472e-b0e1-711740f38956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
